name: between_the_lines
description: A simple Flame game.
version: 0.1.0

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame: ^1.36.0
  flame_audio: ^2.12.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: 1.4.3
  flame_test: 2.2.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/levels/
    - assets/story/
    - assets/dialogues/
    - assets/images/character_full_view/
    - assets/images/character_portrait/
    - assets/images/spritesheets/man/
    - assets/images/spritesheets/woman/
    - assets/images/spritesheets/soldier/
    - assets/images/spritesheets/camera/
    - assets/images/tiles/
    - assets/images/overworld/